import type { Metadata } from "next";
import "@/shared/styles/main.scss";
import Header from "@/widgets/header";
import Get_user from "@/entities/user";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body id="__next">
        <Get_user />
        <Header />

        {children}
      </body>
    </html>
  );
}
