import type { Metadata } from 'next'
import '@/shared/styles/main.scss'
import Header from '@/widgets/header'




export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body id='__next'>
        <Header/>

        {children}
        </body>
    </html>
  )
}
